# Generated by Django 5.1.2 on 2024-10-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='rating',
        ),
        migrations.AddField(
            model_name='userauth',
            name='average_rating',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='userauth',
            name='rating_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
