# Generated by Django 5.1.2 on 2024-10-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_remove_userauth_rating_userauth_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
